---
name: build App
on:
  push: 
    branches: ["main", "dev*", "feat*", "fix*"]


jobs:
  load-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: print env vars
        run: | 
          env